### ISSUE TITLE
mvn clean package failed

### ISSUE THREAD

**Issue by mukkeshmapr** [data-integrations/change-data-capture#21]
1) mvn buld failed after as below 
mvn clean package -Dmaven.test.skip=true -Drat.skip=true

Reported Error 

[INFO] Group ID             : io.cdap.plugin
[INFO] Artifact ID          : cdc-plugins
[INFO] Version              : 2.0.0-SNAPSHOT
[INFO] Base Directory       : /root/change-data-capture
[INFO] Build Directory      : /root/change-data-capture/target
[INFO] Widgets Directory    : widgets
[INFO] Icons Directory      : icons
[INFO] Docs Directory       : docs
[INFO] CDAP Artifacts
[INFO]  system:cdap-data-streams[6.0.0,7.0.0)
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  53.537 s
[INFO] Finished at: 2019-07-31T23:32:59Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.cdap:cdap-maven-plugin:1.1.0:create-plugin-json (create-artifact-config) on project cdc-plugins: Widget file 'CTSQLServer-streamingsource.json' has incorrect JSON. Expected a ',' or '}' at 2701 [character 11 line 77] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
root@cdap-1-vm:~/change-data-capture# 

as , was missing at line 77 in widgets/CTSQLServer-streamingsource.json

73           "widget-type": "textbox",
 74           "label": "Max Batch Size",
 75           "name": "maxBatchSize",
 76           "description": "Size of a record batch per pipeline batch interval"
 77           "widget-attributes" : {
 78             "default" : 100000

added , at   76           "description": "Size of a record batch per pipeline batch interval", 
and ran mvn clean package -Dmaven.test.skip=true -Drat.skip=true

**Comment by albertshau** [comment]
I cannot reproduce this. Are you sure you haven't modified that json file?
