### ISSUE TITLE
 Failed to Upload plugin artifact  jar and json 

### ISSUE THREAD

**Issue by mukkeshmapr** [data-integrations/change-data-capture#22]
Plugin upload is failing for cdc-plugins-2.0.0-SNAPSHOT.json,cdc-plugins-2.0.0-SNAPSHOT.jar

Missing class net.sourceforge.jtds.jdbc.Driver. It may be caused by missing dependency jar(s) in the artifact jar.

**Comment by albertshau** [comment]
I cannot reproduce this either. Are you using the develop branch? The code doesn't even depend on jtds.
